server:
  port: 2333
spring:
  application:
    name: java-pattern-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.101:3306/runoob?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
  #redis配置
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 192.168.10.101
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）默认8
        max-active: 9
        #连接池最大阻塞等待时间，单位毫秒（使用负值表示没有限制）默认-1
        max-wait: -1ms
        #连接池中的最大空闲连接 默认8
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间
    timeout: 2000ms
  cache:
    type: redis
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/    #prefix：指定模板所在的目录
    check-template-location: true    #check-tempate-location: 检查模板路径是否存在
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5    # 用非严格的 HTML
    cache: false    #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  mail:
    host: smtp.qq.com               #邮件服务器地址，以qq邮箱为例
    username: 1647731302@qq.com     #发件人邮箱地址
    password: kbzfyackyjoacdja              #这个密码是邮箱设置里SMTP服务生成的授权码
    default-encoding: UTF-8
  #配置关闭logo
  #  main:
  #    banner-mode: off
  session:
    store-type: none
###########################mybatis配置###############################
#全局映射器启用缓存
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.congee.api.entity
  configuration:
    default-statement-timeout: 25000 #数据库执行超时时间
    default-executor-type: reuse #对于批量更新操作缓存SQL以提高性能
    multiple-result-sets-enabled: true #允许返回不同的结果集以达到通用的效果
    aggressive-lazy-loading: false #按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    lazy-loading-enabled: false #查询时,关闭关联对象及时加载以提高性能
    cache-enabled: true #全局映射器启用缓存
